fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    chocolatey: 'https://github.com/chocolatey/puppet-chocolatey.git'
    powershell: 'https://github.com/joshcooper/puppetlabs-powershell.git'
    staging: 'https://github.com/nanliu/puppet-staging.git'
    helper: 'https://github.com/bodeco/bodeco_module_helper.git'
  symlinks:
    jboss: source_dir
